language: ruby
rvm:
  - 2.3.1
install:
  - bundle update
  - bundle install
  -  travis_wait 30 bundle exec jekyll build
  # - bundle exec htmlproofer ./_site --only-4xx --external_only --url-ignore "http://sda.tech/feed.xml"

script: true
sudo: false
