version: "2"

services:
  sda:
    #build: ./docker/
    image: index.docker.io/smartdataanalytics/site:latest
    restart: unless-stopped
    container_name: sda
    environment:
      - REPO=https://github.com/SmartDataAnalytics/sda.tech
      - BRANCH=master
    ports:
      - 8080:80
    network_mode: "bridge"
    volumes:
      - /var/www/sda.tech/:/data/jekyll/

  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    container_name: watchtower
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   #command: watchtower smartdataanalytics/site:develop --interval 30
    command: sda