version: "2"

services:
  sda:
    #build: ./docker/
    image: index.docker.io/smartdataanalytics/site:develop
    container_name: sda
    hostname: sda.tech
    domainname: sda.tech
    environment:
      - REPO=https://github.com/SmartDataAnalytics/sda.tech
      - BRANCH=develop
      - HOST_NAME=sda.tech
    ports:
      - 8080:80
    volumes:
      - /var/www/sda.tech/:/data/jekyll/

  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    container_name: watchtower
    hostname: sda.tech
    domainname: sda.tech
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   #command: watchtower smartdataanalytics/site:develop --interval 30
    command: sda --interval 30